using CloudX.Azure.Core.Attributes;
using CloudX.Azure.Core.Web;
using NUnit.Framework;
using Cloud.Azure.AwesomePizzaSite.Web.Tests.Meta;
using Cloud.Azure.AwesomePizzaSite.Web.Steps;
using Cloud.Azure.AwesomePizzaSite.Web.Pages.ManageIngredients;
using Cloud.Azure.AwesomePizzaSite.Web.Pages;
using Cloud.Azure.AwesomePizzaSite.Web.Pages.ManagePizza;
using CloudX.Azure.Core.Web.Steps;
using Cloud.Azure.AwesomePizzaSite.Data.Meta;
using Cloud.Azure.AwesomePizzaSite.Data.Model.UI;
using Cloud.Azure.AwesomePizzaSite.Data.Service.UI;

namespace Cloud.Azure.AwesomePizzaSite.Web.Tests.ManageIngredients
{
    public class ManagePizzaTest : BaseTest
    {
        [Test]
        [Component(ComponentName.ManagePizza)]
        [Category(TestType.WebUi)]
        public void AddNewPizzaTest()
        {
            var autogeneratedIngredientModel1 = IngredientService.GenerateIngredient();
            var autogeneratedIngredientModel2 = IngredientService.GenerateIngredient();
            var ingredientList = new List<IngredientModel>()
            {
                autogeneratedIngredientModel1,
                autogeneratedIngredientModel2
            };
            var autogeneratedPizzaModel = PizzaService.GeneratePizza(ingredientList);
            var rowToCheck = new Dictionary<string, string>()
            {
               {ElementTextReference.Table.Pizza.Title, $"{autogeneratedPizzaModel.Title} ({ingredientList.Count} ing.)" },
            };
            Ui.GetPage<PizzaCatalogPage>()
                .Open()
                .MenuItemSelectAndNavigate<ManageIngredientsAddNewPage>(ElementTextReference.Menu.ManageIngredientsAddNew)
                .AddNewIngredient(autogeneratedIngredientModel1)
                .MenuItemSelectAndNavigate<ManageIngredientsAddNewPage>(ElementTextReference.Menu.ManageIngredientsAddNew)
                .AddNewIngredient(autogeneratedIngredientModel2)
                .MenuItemSelectAndNavigate<ManagePizzaAddNewPage>(ElementTextReference.Menu.ManagePizzaAddNew)
                .AddNewPizza(autogeneratedPizzaModel)
                .MenuItemSelectAndNavigate<ManagePizzaListPage>(ElementTextReference.Menu.ManagePizzaList)
                .AddIngredientsToPizza(autogeneratedPizzaModel)
                .PizzasTable
                .VerifyContainsRow(rowToCheck);
        }

    }
}
