using CloudX.Azure.Core.Attributes;
using CloudX.Azure.Core.Web;
using NUnit.Framework;
using Cloud.Azure.AwesomePizzaSite.Web.Tests.Meta;
using Cloud.Azure.AwesomePizzaSite.Web.Steps;
using Cloud.Azure.AwesomePizzaSite.Web.Pages.ManageIngredients;
using Cloud.Azure.AwesomePizzaSite.Web.Pages;
using CloudX.Azure.Core.Utils;
using CloudX.Azure.Core.Web.Steps;
using Cloud.Azure.AwesomePizzaSite.Data.Meta;
using Cloud.Azure.AwesomePizzaSite.Data.Service.UI;

namespace Cloud.Azure.AwesomePizzaSite.Web.Tests.ManageIngredients
{
    public class ManageIngredientsTest: BaseTest
    {
        [Test]
        [Component(ComponentName.ManageIngredients)]
        [Category(TestType.WebUi)]
        public void AddNewIngredientTest()
        {
            var autogeneratedIngredientModel = IngredientService.GenerateIngredient();
            var rowToCheck = new Dictionary<string, string>()
            {
               {ElementTextReference.Table.Ingredients.Title, autogeneratedIngredientModel.Title},
            };

            Ui.GetPage<PizzaCatalogPage>()
                .Open()
                .MenuItemSelectAndNavigate<ManageIngredientsAddNewPage>(ElementTextReference.Menu.ManageIngredientsAddNew)
                .AddNewIngredient(autogeneratedIngredientModel)
                .MenuItemSelectAndNavigate<ManageIngredientsListPage>(ElementTextReference.Menu.ManageIngredientsList)
                .IngredientsListTable
                .VerifyContainsRow(rowToCheck);

           var ingredientCard = Ui.GetPage<ManageIngredientsListPage>()
                .MenuItemSelectAndNavigate<OurIngredientsPage>(ElementTextReference.Menu.OurIngredients)
                .IngredientContainer.IngredientCards.FirstOrDefault(card => card.TitleTextElement.Text.Contains(autogeneratedIngredientModel.Title));

            VerifyThat.NotNull(ingredientCard, "Verify created ingredient displayed on 'Our Ingredients' Page");
            VerifyThat.AreEquals(ingredientCard.DescriptionTextElement.Text, autogeneratedIngredientModel.Description,
                "Verify desvription of ingredient card is as expected");
        }
    }
}
